# Generated by Django 5.2.4 on 2025-07-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_apprenticeproject_mentorproject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apprenticeproject",
            name="apprentice",
        ),
        migrations.RemoveField(
            model_name="apprenticeproject",
            name="project",
        ),
        migrations.RemoveField(
            model_name="mentorproject",
            name="mentor",
        ),
        migrations.RemoveField(
            model_name="mentorproject",
            name="project",
        ),
    ]
