# Generated by Django 5.2.4 on 2025-07-06 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_apprenticeproject_apprentice_and_more"),
        ("user", "0003_remove_apprentice_project_remove_mentor_project_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ApprenticeProject",
        ),
        migrations.DeleteModel(
            name="MentorProject",
        ),
    ]
