# Generated by Django 5.2.4 on 2025-07-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="mentor",
            new_name="assigned_by",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="apprentice",
            new_name="assigned_to",
        ),
    ]
