# Generated by Django 5.2.4 on 2025-07-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_external",
        ),
        migrations.AddField(
            model_name="apprentice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apprentices",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mentor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentors",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="apprentice",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apprentices",
                to="user.mentor",
            ),
        ),
        migrations.AlterField(
            model_name="apprentice",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apprentices",
                to="user.trainer",
            ),
        ),
    ]
