# Generated by Django 5.2.4 on 2025-07-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_apprenticeproject_mentorproject"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apprentice",
            name="project",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="project",
        ),
        migrations.AddField(
            model_name="apprentice",
            name="project",
            field=models.ManyToManyField(
                related_name="apprentices",
                through="projects.ApprenticeProject",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="project",
            field=models.ManyToManyField(
                related_name="mentors",
                through="projects.MentorProject",
                to="projects.project",
            ),
        ),
    ]
