# Generated by Django 5.2.4 on 2025-07-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_apprenticeproject_apprentice_and_more"),
        ("user", "0002_remove_apprentice_project_remove_mentor_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apprentice",
            name="project",
        ),
        migrations.RemoveField(
            model_name="mentor",
            name="project",
        ),
        migrations.AddField(
            model_name="apprentice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apprentices",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentors",
                to="projects.project",
            ),
        ),
    ]
