# Generated by Django 5.2.4 on 2025-07-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        ("projects", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="apprentice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="user.apprentice",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="user.mentor",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="projects.project",
            ),
        ),
    ]
