# Generated by Django 5.2.4 on 2025-07-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rotation", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apprenticerotation",
            name="apprentice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotation_assignments",
                to="user.apprentice",
            ),
        ),
        migrations.AddField(
            model_name="rotation",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rotations",
                to="rotation.department",
            ),
        ),
        migrations.AddField(
            model_name="apprenticerotation",
            name="rotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="apprentice_rotations",
                to="rotation.rotation",
            ),
        ),
    ]
