# Generated by Django 5.2.4 on 2025-07-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rotation", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apprenticerotation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="apprenticerotation",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="apprenticerotation",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="apprenticerotation",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="apprenticerotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("at_halt", "At Halt"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="at_halt",
                max_length=20,
            ),
        ),
    ]
